services:
  rocket:
    image: jjrom/rocket:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./build/rocket/Dockerfile
    ports:
      - ${ROCKET_EXPOSED_PORT:-9999}:80
    environment:
      # Set to 1 if rocket is exposed behind https proxy (e.g. traefik)
      - ROCKET_USE_HTTPS_PROXY=${ROCKET_USE_HTTPS_PROXY:-0}
      - ROCKET_ENVJS_BASE64=${ROCKET_ENVJS_BASE64:-}
      #- ROCKET_APP_TITLE=${ROCKET_APP_TITLE:-rocket}
      #- ROCKET_APP_DESCRIPTION=${ROCKET_APP_DESCRIPTION:-rocket is a STAC viewer}
      #- ROCKET_APP_AUTHOR=${ROCKET_APP_AUTHOR:-jerome.gasperi@gmail.com}
      #- ROCKET_APP_ICON=${ROCKET_APP_ICON:-favicon.ico}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s